modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "kjscc"
version = "${mod_version}"
displayName = "KubeJS ComputerCraft"
authors = "Wolfieboy09"
description = '''
Adding support for ComputerCraft from KubeJS.
Credit go to Prunoideae for the orignal mod.
'''
# logoFile = "icon.png"

[[dependencies.kjscc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kjscc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.kjscc]]
modId = "computercraft"
mandatory = true
ordering = "AFTER"
side = "BOTH"
versionRange = "[*,)"